# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_taxt', models.TextField(max_length=200, verbose_name='Превью')),
                ('article_text', models.TextField(max_length=200, verbose_name='Контент')),
                ('article_date', models.DateTimeField(verbose_name='Дата')),
                ('article_likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
